CREATE TABLE users (id BIGSERIAL PRIMARY KEY, sso_sub VARCHAR(255) NOT NULL UNIQUE, name VARCHAR(255) NOT NULL DEFAULT '', nickname VARCHAR(255) NOT NULL DEFAULT '', email VARCHAR(255) NOT NULL DEFAULT '', avatar TEXT NOT NULL DEFAULT '', role VARCHAR(16) NOT NULL, status VARCHAR(16) NOT NULL DEFAULT 'active', created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
-- statement-breakpoint
CREATE UNIQUE INDEX users_single_owner ON users ((role)) WHERE role = 'owner';
-- statement-breakpoint
CREATE TABLE sessions (id VARCHAR(96) PRIMARY KEY, user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE, expires_at TIMESTAMPTZ NOT NULL, revoked_at TIMESTAMPTZ NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
-- statement-breakpoint
CREATE INDEX sessions_user_idx ON sessions(user_id);
-- statement-breakpoint
CREATE TABLE business_plans (id BIGSERIAL PRIMARY KEY, user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE, title VARCHAR(255) NOT NULL, filename VARCHAR(255) NOT NULL, mime_type VARCHAR(128) NOT NULL, object_key VARCHAR(512) NOT NULL, size_bytes BIGINT NOT NULL, version INT NOT NULL DEFAULT 1, status VARCHAR(24) NOT NULL DEFAULT 'uploaded', created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
-- statement-breakpoint
CREATE TABLE analysis_jobs (id BIGSERIAL PRIMARY KEY, plan_id BIGINT NOT NULL REFERENCES business_plans(id) ON DELETE CASCADE, status VARCHAR(24) NOT NULL DEFAULT 'queued', error TEXT NOT NULL DEFAULT '', result JSONB NULL, summary TEXT NOT NULL DEFAULT '', created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
-- statement-breakpoint
CREATE TABLE app_settings (key VARCHAR(64) PRIMARY KEY, value TEXT NOT NULL, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
