CREATE TABLE users (id BIGINT AUTO_INCREMENT PRIMARY KEY, sso_sub VARCHAR(255) NOT NULL UNIQUE, name VARCHAR(255) NOT NULL DEFAULT '', nickname VARCHAR(255) NOT NULL DEFAULT '', email VARCHAR(255) NOT NULL DEFAULT '', avatar TEXT NOT NULL, role VARCHAR(16) NOT NULL, status VARCHAR(16) NOT NULL DEFAULT 'active', created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
-- statement-breakpoint
CREATE INDEX users_role_idx ON users(role);
-- statement-breakpoint
CREATE TABLE sessions (id VARCHAR(96) PRIMARY KEY, user_id BIGINT NOT NULL, expires_at TIMESTAMP NOT NULL, revoked_at TIMESTAMP NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT sessions_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE);
-- statement-breakpoint
CREATE TABLE business_plans (id BIGINT AUTO_INCREMENT PRIMARY KEY, user_id BIGINT NOT NULL, title VARCHAR(255) NOT NULL, filename VARCHAR(255) NOT NULL, mime_type VARCHAR(128) NOT NULL, object_key VARCHAR(512) NOT NULL, size_bytes BIGINT NOT NULL, version INT NOT NULL DEFAULT 1, status VARCHAR(24) NOT NULL DEFAULT 'uploaded', created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT plans_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE);
-- statement-breakpoint
CREATE TABLE analysis_jobs (id BIGINT AUTO_INCREMENT PRIMARY KEY, plan_id BIGINT NOT NULL, status VARCHAR(24) NOT NULL DEFAULT 'queued', error TEXT NOT NULL, result JSON NULL, summary TEXT NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT jobs_plan_fk FOREIGN KEY (plan_id) REFERENCES business_plans(id) ON DELETE CASCADE);
-- statement-breakpoint
CREATE TABLE app_settings (`key` VARCHAR(64) PRIMARY KEY, value TEXT NOT NULL, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
